
CREATE TABLE SUPPLIER(
	SUPPLIER_CODE INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  	SUPPLIER_NAME VARCHAR(255) NOT NULL,
  	CITY VARCHAR(255) NOT NULL
);

CREATE TABLE PART(
	PART_CODE INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  	NAME_PART VARCHAR(255) NOT NULL,
  	PRICE DECIMAL(18,2) NOT NULL
);

CREATE TABLE CAR(
	CAR_CODE INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  	NAME_CAR VARCHAR(255) NOT NULL,
  	TYPE VARCHAR(255) NOT NULL
);

CREATE TABLE SUPPLY (
	SUPPLIER_CODE INTEGER,
	PART_CODE INTEGER,
	CAR_CODE INTEGER,
	FOREIGN KEY(SUPPLIER_CODE) REFERENCES SUPPLIER(SUPPLIER_CODE),
  	FOREIGN KEY(PART_CODE) REFERENCES PART(PART_CODE),
  	FOREIGN KEY(CAR_CODE) REFERENCES CAR(CAR_CODE)
);




INSERT INTO SUPPLIER(
	SUPPLIER_NAME,
  	CITY
)
VALUES
('HYPERX', 'SÃO PAULO'),
('CHEVROLET', 'VITORIA'),
('HONDA', 'VITORIA');


INSERT INTO PART(
	NAME_PART,
  	PRICE 
)
VALUES
('MOTOR', 4590.12),
('MOTOR', 7950.47),
('MEMÓRIA', 199.93);


INSERT INTO CAR(
	NAME_CAR,
  	TYPE
)
VALUES
('KOMBI', 'X'),
('FERRARI', 'Y'),
('LAMBORGHINI', 'Z');


INSERT INTO SUPPLY(
	SUPPLIER_CODE,
	PART_CODE,
	CAR_CODE
)
VALUES
(2, 1, 1),
(2, 2, 1),
(2, 1, 2),
(2, 2, 2),
(3, 1, 1),
(3, 1, 2);


SELECT
	SR.SUPPLIER_NAME,
    PT.PRICE
FROM
	SUPPLIER SR
    	INNER JOIN
        	SUPPLY SY
            	ON 
                	SY.SUPPLIER_CODE = SR.SUPPLIER_CODE
        INNER JOIN
        	PART PT
            	ON
                	PT.PART_CODE = SY.PART_CODE
        INNER JOIN
        	CAR CR
            	ON
                	CR.CAR_CODE = SY.CAR_CODE
        
WHERE
	SR.CITY = 'VITORIA' AND
    PT.NAME_PART = 'MOTOR' AND
    CR.NAME_CAR = 'KOMBI';
